services:
  botserver:
    build: .
    volumes:
      - intro-bot-sounds:/usr/src/app/src/sounds
      - intro-bot-data:/usr/src/app/src/data
    restart: unless-stopped

volumes:
  intro-bot-sounds:
  intro-bot-data: